samples_file: "config/samples_big.csv"
workflow_mode: "supertree"
supertree_method: "fasturec"

experiments:
  include_paralogs: True
  filter_bootstraps: True
  min_tree_support: 0.7

clustering:
  min_seq_id: 0.30
  coverage: 0.5
  min_species: 8
  outgroups: ["O01", "O02", "O03", "O04", "O05"]

alignment:
  mafft_args: "--auto --quiet"
  trimal_method: "-automated1"

consensus:
  minsup: 0.5
  threads: 4

gene_tree_params:
  ML:
    flags: "-m LG+G4 -bb 1000"
  NJ:
    flags: "-fastest -quiet"

tree:
  bootstrap: 1000
  gene_tree_method: "ML"
  model: "LG+G4"

tree_methods: ["ML"]

embeddings:
  dim: 64
  epochs: 500
  n_perturbations: 5
  noise_scale: 0.05

structure:
  max_length: 500
  tree_method: "nj"

resources:
  download: 2
  clustering: 4
  clustering_mem_mb: 8000
  orthologs: 4
  orthologs_mem_mb: 16000
  mafft: 2
  trimal: 2
  genetree: 2
  supertree: 4
